#pragma once

#include <string>

enum dir4_t
{
	NORTH=0,
	EAST,
	SOUTH,
	WEST,

	TOP=NORTH,
	RIGHT=EAST,
	BOTTOM=SOUTH,
	LEFT=WEST
};

enum dir8_t
{
	d8_NORTH=0,
	d8_NORTHEAST,
	d8_EAST,
	d8_SOUTHEAST,
	d8_SOUTH,
	d8_SOUTHWEST,
	d8_WEST,
	d8_NORTHWEST
};

enum inventory_t
{
	INV_FUEL,
	INV_BURNT_RESULT,
	INV_CHEST,
	INV_FURNACE_SOURCE,
	INV_FURNACE_RESULT,
	INV_FURNACE_MODULES,
	INV_PLAYER_QUICKBAR,
	INV_PLAYER_MAIN,
	INV_PLAYER_GUNS,
	INV_PLAYER_AMMO,
	INV_PLAYER_ARMOR,
	INV_PLAYER_TOOLS,
	INV_PLAYER_VEHICLE,
	INV_PLAYER_TRASH,
	INV_GOD_QUICKBAR,
	INV_GOD_MAIN,
	INV_ROBOPORT_ROBOT,
	INV_ROBOPORT_MATERIAL,
	INV_ROBOT_CARGO,
	INV_ROBOT_REPAIR,
	INV_ASSEMBLING_MACHINE_INPUT,
	INV_ASSEMBLING_MACHINE_OUTPUT,
	INV_ASSEMBLING_MACHINE_MODULES,
	INV_LAB_INPUT,
	INV_LAB_MODULES,
	INV_MINING_DRILL_MODULES,
	INV_ITEM_MAIN,
	INV_ROCKET_SILO_ROCKET,
	INV_ROCKET_SILO_RESULT,
	INV_CAR_TRUNK,
	INV_CAR_AMMO,
	INV_CARGO_WAGON,
	INV_TURRET_AMMO,
	INV_BEACON_MODULES
};

extern std::string inventory_names[];
